apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-processing-ms-webapi-hpa
  namespace: video-processing-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-processing-ms-webapi-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80